spring:
  application:
   name: batch-mongo
  sql:
    init:
      mode: never

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    jdbcUrl: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  mongodb:
    uri: ${MONGO_URL}


  main:
    allow-bean-definition-overriding: true

app:
  paths:
    resource: ${PATH_RESOURCE}
    datasource: ${DATA_SOURCE}
    destination: ${PATH_DESTINY}
    collection: ${COLLECTION_MONGO}

